SELECT 
		 [ProductKey] AS [ProductID]
		,[ProductAlternateKey] AS [ProductCode]
--		,[ProductSubcategoryKey]
--		,[WeightUnitMeasureCode]
--		,[SizeUnitMeasureCode]
		,[EnglishProductName] AS [Product Name]
		,pc.EnglishProductCategoryName AS [ProductCategory]
		,ps.EnglishProductSubcategoryName AS [ProductSubcategory]
--		,[SpanishProductName]
--		,[FrenchProductName]
--		,[StandardCost]
--		,[FinishedGoodsFlag]
		,[Color]
--		,[SafetyStockLevel]
--		,[ReorderPoint]
--		,[ListPrice]
		,[Size]
--		,[SizeRange]
--		,[Weight]
--		,[DaysToManufacture]
		,[ProductLine]
--		,[DealerPrice]
--		,[Class]
--		,[Style]
		,[ModelName]
--		,[LargePhoto]
		,[EnglishDescription] AS [Product Description]
--		,[FrenchDescription]
--		,[ChineseDescription]
--		,[ArabicDescription]
--		,[HebrewDescription]
--		,[ThaiDescription]
--		,[GermanDescription]
--		,[JapaneseDescription]
--		,[TurkishDescription]
--		,[StartDate]
--		,[EndDate]
--		,[Status]
		,ISNULL (p.Status, 'Not Available') AS Status
  FROM [AdventureWorksDW2019].[dbo].[DimProduct] AS p

  LEFT JOIN dbo.DimProductSubcategory AS ps ON ps.ProductSubcategoryKey = p.ProductSubcategoryKey
  LEFT JOIN dbo.DimProductCategory AS pc ON pc.ProductCategoryKey = ps.ProductCategoryKey
